### **Date time Convert**
---

In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [4]:
# Convert string into datetime format
date['date'] = pd.to_datetime(date['date'])

In [5]:
date_var = date['date']
date['year'] = date_var.dt.year
date['month'] = date_var.dt.month_name()
date['day'] = date_var.dt.day

In [6]:
date.head()

        date  product_id  city_id  orders  year     month  day
0 2019-12-10        5628       25       3  2019  December   10
1 2018-08-15        3646       14     157  2018    August   15
2 2018-10-23        1859       25       1  2018   October   23
3 2019-08-17        7292       25       1  2019    August   17
4 2019-01-06        4344       25       3  2019   January    6

In [7]:
# Extract Time
time['date'] = pd.to_datetime(time['date'])

In [8]:
time_var = time['date']
time['Hour'] = time_var.dt.hour
time['Min'] = time_var.dt.minute
time['Sec'] = time_var.dt.second

In [9]:
a = pd.Timestamp.today()
time.head()

,date,msg,Hour,Min,Sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

### **Date Difference**
---

In [10]:
date['date_diff'] = (pd.Timestamp.today() - date['date']).dt.days
date.head()

        date  product_id  city_id  orders  year     month  day  date_diff
0 2019-12-10        5628       25       3  2019  December   10       2314
1 2018-08-15        3646       14     157  2018    August   15       2796
2 2018-10-23        1859       25       1  2018   October   23       2727
3 2019-08-17        7292       25       1  2019    August   17       2429
4 2019-01-06        4344       25       3  2019   January    6       2652

### **Sort Values**
---

In [11]:
date = date.sort_values('date')
date.head()

          date  product_id  city_id  orders  year month  day  date_diff
319 2018-07-10        6283       14       2  2018  July   10       2832
36  2018-07-13        3432       13      28  2018  July   13       2829
766 2018-07-13        3454       14       8  2018  July   13       2829
467 2018-07-14        1114       13      90  2018  July   14       2828
428 2018-07-14        4183       22       8  2018  July   14       2828

### **Filtering**
---

In [12]:
date[date['date'] > '2018-07-14'].head()

          date  product_id  city_id  orders  year month  day  date_diff
602 2018-07-15        3497       26     234  2018  July   15       2827
742 2018-07-15        3627       13      21  2018  July   15       2827
585 2018-07-16        5738       13      39  2018  July   16       2826
836 2018-07-17        2430       23       4  2018  July   17       2825
945 2018-07-17        2568       22       8  2018  July   17       2825

### **Convert Datetime into Nanoseconds**
---

In [13]:
date['date_numeric'] = date['date'].astype('int64')
date.head()

,date,product_id,city_id,orders,year,month,day,date_diff,date_numeric
319,2018-07-10,6283,14,2,2018,July,10,2832,1531180800000000
36,2018-07-13,3432,13,28,2018,July,13,2829,1531440000000000
766,2018-07-13,3454,14,8,2018,July,13,2829,1531440000000000
467,2018-07-14,1114,13,90,2018,July,14,2828,1531526400000000
428,2018-07-14,4183,22,8,2018,July,14,2828,1531526400000000

### **Relative Days**
---

In [14]:
date['days_since'] = (date['date'] - date['date'].min()).dt.days
date.head(20)

,date,product_id,city_id,orders,year,month,day,date_diff,date_numeric,days_since
319,2018-07-10,6283,14,2,2018,July,10,2832,1531180800000000,0
36,2018-07-13,3432,13,28,2018,July,13,2829,1531440000000000,3
766,2018-07-13,3454,14,8,2018,July,13,2829,1531440000000000,3
467,2018-07-14,1114,13,90,2018,July,14,2828,1531526400000000,4
428,2018-07-14,4183,22,8,2018,July,14,2828,1531526400000000,4
602,2018-07-15,3497,26,234,2018,July,15,2827,1531612800000000,5
742,2018-07-15,3627,13,21,2018,July,15,2827,1531612800000000,5
585,2018-07-16,5738,13,39,2018,July,16,2826,1531699200000000,6
836,2018-07-17,2430,23,4,2018,July,17,2825,1531785600000000,7
945,2018-07-17,2568,22,8,2018,July,17,2825,1531785600000000,7
365,2018-07-18,6248,4,2,2018,July,18,2824,1531872000000000,8
61,2018-07-20,7025,14,22,2018,July,20,2822,1532044800000000,10
956,2018-07-20,7334,21,9,2018,July,20,2822,1532044800000000,10
822,2018-07-21,868,18,25,2018,July,21,2821,1532131200000000,11
230,2018-07-22,7554,13,12,2018,July,22,2820,1532217600000000,12
577,2018-07-22,2974,26,15,2018,July,22,2820,1532217600000000,12
842,2018-07-23,2190,14,3,2018,July,23,2819,1532304000000000,13
133,2018-07-23,6564,18,3,2018,July,23,2819,1532304000000000,13
798,2018-07-23,154,26,4,2018,July,23,2819,1532304000000000,13
385,2018-07-24,4306,14,11,2018,July,24,2818,1532390400000000,14